# Form implementation generated from reading ui file 'infowindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 204)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 391, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 140, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 239, 0);\n"
"border: none;\n"
"padding-top: 5px;\n"
"color: rgb(60, 4, 57);\n"
"border-right: 3px solid rgb(191, 198, 0);\n"
"border-bottom: 4px solid rgb(191, 198, 0);\n"
"border-left:none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(238, 243, 0);\n"
"border-right: 3px solid rgb(191, 198, 0);\n"
"border-bottom: 4px solid rgb(191, 198, 0);\n"
"border-left:none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 213, 0);\n"
"border-left: 4px solid rgb(191, 198, 0);\n"
"border-top: 5px solid rgb(191, 198, 0);\n"
"border-right:none;\n"
"padding-top: -5px;\n"
"border-bottom:none\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 140, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 239, 0);\n"
"border: none;\n"
"padding-top: 5px;\n"
"color: rgb(60, 4, 57);\n"
"border-right: 3px solid rgb(191, 198, 0);\n"
"border-bottom: 4px solid rgb(191, 198, 0);\n"
"border-left:none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(238, 243, 0);\n"
"border-right: 3px solid rgb(191, 198, 0);\n"
"border-bottom: 4px solid rgb(191, 198, 0);\n"
"border-left:none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(206, 213, 0);\n"
"border-left: 4px solid rgb(191, 198, 0);\n"
"border-top: 5px solid rgb(191, 198, 0);\n"
"border-right:none;\n"
"padding-top: -5px;\n"
"border-bottom:none\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "INFORMACJA"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Algorytm działa lepiej, gdy wybierzesz</span></p><p align=\"center\"><span style=\" font-size:14pt;\">mutację!</span></p><p align=\"center\"><span style=\" font-size:11pt;\">Czy na pewno chcesz kontynuować?</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Tak"))
        self.pushButton_2.setText(_translate("MainWindow", "Nie"))
